"""empty message

Revision ID: 4b324f736a0a
Revises: 748ee717d1a0
Create Date: 2021-04-07 15:58:02.006822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b324f736a0a'
down_revision = '748ee717d1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ventas', sa.Column('descripcion', sa.String(), nullable=True))
    op.drop_column('Ventas', 'drescipcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ventas', sa.Column('drescipcion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Ventas', 'descripcion')
    # ### end Alembic commands ###
