"""empty message

Revision ID: 748ee717d1a0
Revises: 53547c9dd79d
Create Date: 2021-04-07 15:41:11.575993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748ee717d1a0'
down_revision = '53547c9dd79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drescipcion', sa.String(), nullable=True),
    sa.Column('precio', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.drop_table('Ventas')
    # ### end Alembic commands ###
