"""empty message

Revision ID: d5c5eb0b7cf2
Revises: 4b324f736a0a
Create Date: 2021-04-07 15:59:19.481838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c5eb0b7cf2'
down_revision = '4b324f736a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductoVentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ventas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Ventas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Ventas_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('precio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Ventas_pkey')
    )
    op.drop_table('ProductoVentas')
    # ### end Alembic commands ###
